### ISSUE TITLE
add support for esbuild options

### ISSUE THREAD

**Issue by mulfyx** [folke/esbuild-runner#14]
maybe add support for passing  esbuild options for 'install' functions? like this:
```js
const { install } = require('esbuild-runner');

install({
  type: 'transform',
  debug: false,
  esbuild: {
    target: 'esnext',
    plugins: [...]
  }
});
```

**Comment by glromeo** [comment]
although an API could be nice, given that esbuild-runner is already well integrated with Jest I sponsor a config file e.g:
**esbuild.config.js**
```javascript
module.exports = {
    target: 'esnext',
    plugins: [...]
}
```

**Comment by folke** [comment]
I'll see if I can add both the extra options to the API and the config file

**Comment by seangenabe** [comment]
I'm running into issues regarding evaluating CommonJS and this would probably help.

**Comment by folke** [comment]
I just made a new release that supports passing options to the API and reading of `esbuild.config.js`

**Comment by pincman** [comment]
@folke `error: Cannot use plugins in synchronous API calls`
