### ISSUE TITLE
esbuild.config.js is too generic naming

### ISSUE THREAD

**Issue by IlyaSemenov** [folke/esbuild-runner#22]
I believe `esbuild.config.js` is too generic naming. It misleads the reader as if that were esbuild config, which it is not. It also 'squats' the place for the actual esbuild config, for example if developer wanted to keep and reuse esbuild settings between different components of the project (such as: esbuild-runner, estrella, vite, esbuild-loader, etc.)

I believe `esbuild-runner.config.js` would be better naming, directly explaining the purpose of the file.

**Comment by folke** [comment]
You are totally right about this. Didn't think that one through. I'll change it!

**Comment by folke** [comment]
Just released a new version with the updates https://github.com/folke/esbuild-runner/releases/tag/2.0.0
