### ISSUE TITLE
Configuration option loader(s) is ignored

### ISSUE THREAD

**Issue by karrikuivanen** [folke/esbuild-runner#24]
Hi,

in the same vein as #23, unless I'm mistaken, it seems that the `--loader` esbuild option is not currently supported.

Similarly to the `externals` issue, a merge of user provided loaders with the default stack could be considered.

My use case is testing modules that use static binary assets.

My `esbuild-runner-config.js`:
```javascript
module.exports = {
  type: 'bundle',
  esbuild: {
    target: 'node14',
    format: 'cjs',
    loader: {
      '.png': 'binary'
    }
  }
}
```

Result:
```
 > lib/loader-issue.js:1:16: error: No loader is configured for ".png" files: assets/img/image.png
    1 │ import pngImage from '../assets/img/image.png'
      ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~
```

Thanks for a great tool!

**Comment by gustavoschmidt** [comment]
loaderS :)

**Comment by folke** [comment]
I just added support for custom loaders. @gustavoschmidt the option is [loader](https://esbuild.github.io/api/#loader) without the `s` ;)

`target` was another option that was overshadowed by esbuild-runner. Also fixed.

Let me know if you have any more issues with this.

Thank you for reporting!
