### ISSUE TITLE
TypeError: Jest: a transform must export something.

### ISSUE THREAD

**Issue by ebeloded** [folke/esbuild-runner#26]
Getting an error when trying to use esbuild-runner with the latest version of Jest. Config is simple:

```
transform: {
    '\\.ts$': 'esbuild-runner/jest',
  },
```

Versions:
jest: 27.0.4
esbuild-runner: 2.2.0

**Comment by esturcke** [comment]
I just ran into this in a new project as well. I was able work around this by creating an `./esr-jest`:

```js
const { process } = require("esbuild-runner/jest")
module.exports = { process }
```

And then in `./jest.config.js`:

```
  transform: {
    "^.+\\.tsx?$": "./esr-jest",
  },
```

I'm not sure why this works, but I'm guessing something to do with how Jest's `requireOrImportModule` works.

**Comment by schickling** [comment]
Thanks for this workaround @esturcke 

@folke could this be fixed in the library itself as well? 🙏

**Comment by folke** [comment]
I just released an update that fixes this

**Comment by ilteoood** [comment]
Hi,
I've the same problem, even with the latest version.
Do you guys any suggestion?

I've configured the transform in this way:

`
"transform": {
      "^.+\\.(js|jsx|ts|tsx)$": "esbuild-runner/jest"
    },
`

**Comment by JounQin** [comment]
<img width="664" alt="image" src="https://user-images.githubusercontent.com/8336744/169761288-504ef6d2-a4cd-48aa-bea8-69eb1f500803.png">

@folke This issue should not be closed.
